apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-dsn-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # Enable CORS by adding these annotations
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - specif-dsn.lab.sspcloud.fr
  rules:
  - host: specif-dsn.lab.sspcloud.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-dsn-service
            port:
              number: 80